### DISCUSSION TITLE
Onboarding Flow Optimization

### DISCUSSION THREAD

**Discussion by 0x4007** [ubiquity/ubiquibot#182] [Specifications]
### Definitions

UbiquiBot - "production instance"
UbiquiBot[dev] - "dev instance"

### Secrets 
- `app_id` - should be hardcoded in the app. Make sure to accomodate the dev instance though as technically it has a separate app id. 
- open ssh key - this should be ignored by the production instance and required by the dev instance because from what I understand it is necessary to automatically build `index.js` every time code changes are pushed.

### Misc
- The `ubiquity-bounties` mannequin account should no longer be a dependency. It was a tedious extra step to add it to the partner organization. We should support making "no assignee" the "devpool" mannequin, meaning, if the issue is not assigned to somebody then its considered an open task for the devpool

**Comment by 0x4007** [comment]
# Secrets Management

In our `bounty-bot` repo, we have the production instance, which is useful for comparing stable behavior; running at the same time as the dev instance, which is useful for live development and seeing the latest changes. 

- We need to figure out the best way to be able to test stable ("production") vs dev instances of the bot.
- The reason why this could be tricky is because they both use the same code. 
- A proposed solution: we need a config in the `.yml` file to run for the dev instance. 

```yml
      - name: Invoke the UbiquiBot
        id: UbiquiBot
        uses: ./bin
        with:
          GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        env:
          FOLLOW_UP_TIME: '4 days'
          DISQUALIFY_TIME: '7 days'
          DEV: true
```
