### ISSUE TITLE
Auto Labeling Configuration

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#500]
The auto-label feature (the one where if an issue is submitted with no labels then the bot automatically adds `Price` and `Time` needs to be off by default, and configurable in the `ubiquibot-config.yml`

We also need full documentation around the config properties because I'm not even familiar with how to adjust this.

### Schema

- This is automatically added for every new issue opened without existing labels. 
- User specific config will be handled by a future bounty. 

```yml
default-labels:
    - "Time: <1 Hour"
    - "Priority: 0 (Normal)"
```

**Comment by 0xcodercrane** [comment]
We didn't merge the corresponding PR yet. https://github.com/ubiquity/ubiquibot/pull/484

**Comment by whilefoo** [comment]
So this feature would implement a new toggle in the config like `auto-label-mode: true/false` that would enable or disable the automatic labeling?

Should I put the documentation of the configuration in the README?

**Comment by pavlovcik** [comment]
> We didn't merge the corresponding PR yet. https://github.com/ubiquity/ubiquibot/pull/484

That's not the subject of this bounty. This bounty is for configuration. The one you linked is to make the labels "effective" and actually fund the issue with a bounty reward.

**Comment by rndquu** [comment]
Let's keep default labels in the bot's config for the 1st feature iteration.

Also if the "default labels" feature is on then after an issue has been created an admin should be able to delete automatically added labels (in order to transform an issue to a "meta" issue with subtasks) and the bot **should not** add default labels if they are deleted manually.

The following example also looks good:
```yml
default-labels:
  global:
    - "Time: <1 Hour"
    - "Priority: 0 (Normal)"
  users:
    pavlovcik:
      - "Time: <1 Hour"
      - "Priority: 0 (Normal)"
```
