### ISSUE TITLE
`issue-creator-multiplier` formula

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#583]
Same way to how we adjusted the `price-multiplier` formula to work with `1` as the input value (instead of `1000`) we should do the same for `issue-creator-multiplier`.

              I can't directly suggest on the earlier lines but I think we should do the following defaults:

```yml
price-multiplier: 1
issue-creator-multiplier: 2 # we need to convert this formula to work with 2, not 2000
time-labels: ... # these should be dynamically generated 

```

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/558#discussion_r1285255602_
