### ISSUE TITLE
Config nested inheritance

### ISSUE THREAD

**Issue by whilefoo** [ubiquity/ubiquibot#648]
We only have inheritance on top level properties, so if `incentives` property is missing from repo and org config, it will use the whole `incentives` property from default config. Nested properties don't have inheritance (if `h1` is not present in repo config it won't inherit from default config), that is something I was meaning to make an issue for.

_Originally posted by @whilefoo in https://github.com/ubiquity/ubiquibot/pull/545#discussion_r1297266427_

For example if we have a organization config:
```yaml
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
    totals:
      word: 0.1
```

and repo config:
```yaml
incentives:
  comment:
    elements:
      code: 10
      li: 3
    totals:
      word: 0.1
```

currently because repo config overrides organization config and we parse only top-level properties, the merged config will be the same as repo config, but we want to have inheritance on nested properties too, so the merge config should look like this:
```yaml
incentives:
  comment:
    elements:
      code: 10
      img: 5
      li: 3
      h1: 1
    totals:
      word: 0.1
```

**Comment by pavlovcik** [comment]
Do you think my proposal addresses this? https://github.com/ubiquity/ubiquibot/issues/647

**Comment by whilefoo** [comment]
Your solution doesn't work if the `key` are just top-level properties but if we did that recursively for every property then it would work.

**Comment by whilefoo** [comment]
We can do this using `lodash` function `merge` [(example)](https://jsfiddle.net/cex36w29/)

**Comment by pavlovcik** [comment]
> #### Task Creator Reward
> ### [ **whilefoo: [ CLAIM 83.2 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiODMyMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI5ODIxODc5ODUxMjk3ODA4NjYyNTg1NzY0OTYwMDY0NzcxNDk3NTY1NDI5MDM5MDk3NjQwODMzMzU4MzkxNTA0MDg3MzM3NTA0MzYxNiIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4QTBCMTFGNDc0ZDhFQ0UxMjA1ZDM4YzY2ZDVGMmJFODkxNzY3NWQ2MCIsInJlcXVlc3RlZEFtb3VudCI6IjgzMjAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5ZDU2M2IzODY3ZTllYjc5M2E5NWJmZDM5YjcxYmEwYTczMzdjY2RmNWNlZmRmMmU4YjFlMjY2OGJiMjM0ZTA5NjhhNDhjYjkyZThkZDcxMDEyMGVjY2M4MzJkMTYxMDliZmUzMmU5MDI0OGUxZWMyNzA3YmMxODY3NmU2MjhlNzFiIn0=&network=100)

This is a lot higher than expected. 

Is it counting words inside of code blocks? The code blocks should just count for like $5 for example. With the 4x multiplier thats $20.

**Comment by pavlovcik** [comment]
> Yes I think it's also counting words in code blocks and the top quote and italics

Yikes. We should set a special property on every element that indicates whether the parser should recurse or stop.

For example:

```yaml
incentives: 
  comments:
    elements:
      code: [ 5, false ]
```

This doesn't seem very expressive but I hope we can improve this proposal.
