### ISSUE TITLE
`ignore-children` comment incentive config

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#772]
> Yes I think it's also counting words in code blocks and the top quote and italics

Yikes. We should set a special property on every element that indicates whether the parser should recurse or stop.

```yaml
incentives: 
  comments:
    totals:
      word: 0.1
    elements:
      rewards:
        code: 5
        p: 0.1
        a: 5
    ignore-children: code, i, blockquote
      
```

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/648#issuecomment-1720029504_
