### ISSUE TITLE
Invalid Property Error Logging

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#799]
1. It would be nice if the bot replies to invocations with the error in order to make it clear why it's down. Fortunately we have logs to rely on but if it comments the error directly then it should lead to an even faster diagnosis. 
2. The bot should not crash if there are extraneous properties. It should throw a warning in the logs though, and its comments.

Also would be great if this specific property error was fixed too. 

https://github.com/ubiquity/ubiquibot/commit/4b4c8f89909424f1c4ca37ebd16b513dae42816b

Invalid config according to the logs

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/793#issuecomment-1732172718_

**Comment by gitcoindev** [comment]
Testing was quite tricky but I finally got it. QA passes both for situations when unnecessary properties were defined in the config:

(https://github.com/gitcoindev/ubiquibot/issues/12#issuecomment-1756275530)
`Invalid repo config: data must NOT have additional properties. Unnecessary properties: price-multiplier`

and when some required properties are missing:

(https://github.com/gitcoindev/ubiquibot/issues/12#issuecomment-1756283392)
`Invalid repo config: data/newContributorGreeting must have required property 'footer'.`

I will open a pull request soon.

**Comment by Keyrxng** [comment]
So what exactly should the repo config look like as I've pulled a fresh dev branch and the only property that doesn't flag an issue for me at least is incentives... I thought it was my config so I stole rndquu's org config and same thing.

```yaml
evmNetworkId: 100
issueCreatorMultiplier: 1
timeLabels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priorityLabels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
defaultLabels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
paymentPermitMaxPrice: 1000
commentIncentives: true
maxConcurrentAssigns: 5
promotionComment: ""
assistivePricing: true
registerWalletWithVerification: false
commandSettings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: autopay
    enabled: true
  - name: allow
    enabled: true
  - name: help
    enabled: true
  - name: payout
    enabled: true
  - name: ask
    enabled: true
disableAnalytics: false
enableAccessControl:
  label: true
  organization: true
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
      li: 0.5
      a: 0.5
      blockquote: 0
    totals:
      word: 0.1
```
      
      
      
![image](https://github.com/ubiquity/ubiquibot/assets/106303466/d11b3307-a87f-4271-ad6a-78671245b6ab)
