### ISSUE TITLE
Draft: Custom Events Per User

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot#916]
I was thinking that with the new plugins architecture, that it would be feasible to map specific events invoked by specific users to trigger specific plugins. 

For example:

```yml
*:
   <all events>
pavlovcik: 
   issue_comment.created: 
      workflow: pavlovcik/chatgpt-comment-summary
   issue_comment.edited: 
      workflow: pavlovcik/comment-spellcheck

```

The idea being that we can map "user macros" to specific events.
